language: csharp
solution: GenerateFakeData.sln
script:
  - msbuild /p:Configuration=Release GenerateFakeData.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./TestingProjectGenerateFakeData/bin/Release/TestingProjectGenerateFakeData.dll