//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenerateFakeData.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenerateFakeData.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;persons&quot;: [{
        ///		&quot;name&quot;: &quot;Annemette P.&quot;,
        ///		&quot;surname&quot;: &quot;Nilsson&quot;,
        ///		&quot;gender&quot;: &quot;female&quot;
        ///	}, {
        ///		&quot;name&quot;: &quot;Freja O.&quot;,
        ///		&quot;surname&quot;: &quot;Thygesen&quot;,
        ///		&quot;gender&quot;: &quot;female&quot;
        ///	}, {
        ///		&quot;name&quot;: &quot;Anna S.&quot;,
        ///		&quot;surname&quot;: &quot;Jespersen&quot;,
        ///		&quot;gender&quot;: &quot;female&quot;
        ///	}, {
        ///		&quot;name&quot;: &quot;Rosa M.&quot;,
        ///		&quot;surname&quot;: &quot;Bang&quot;,
        ///		&quot;gender&quot;: &quot;female&quot;
        ///	}, {
        ///		&quot;name&quot;: &quot;Nicolai T.&quot;,
        ///		&quot;surname&quot;: &quot;Bech&quot;,
        ///		&quot;gender&quot;: &quot;male&quot;
        ///	}, {
        ///		&quot;name&quot;: &quot;Mimir S.&quot;,
        ///		&quot;surname&quot;: &quot;Krogh&quot;,
        ///		&quot;gender&quot;: &quot;male&quot;
        ///	}, {
        ///		&quot;name&quot;: &quot;Mike M.&quot;,
        ///		&quot;surname&quot;: &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string person_names {
            get {
                return ResourceManager.GetString("person-names", resourceCulture);
            }
        }
    }
}
